repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --manifest-path src-tauri/Cargo.toml --all -- --check
        language: system
        pass_filenames: false
        types_or: [rust, toml]

      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --manifest-path src-tauri/Cargo.toml --all-targets --all-features -- -D warnings
        language: system
        pass_filenames: false
        types_or: [rust, toml]

      - id: cargo-test
        name: cargo test
        entry: cargo test --manifest-path src-tauri/Cargo.toml --all-targets --all-features
        language: system
        pass_filenames: false
        stages: [pre-push]
        types_or: [rust, toml]
